[package]
name = "rusty_advent"
version = "0.1.0"
authors = ["nedmv <nedmvl@rambler.ru>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
counter = "0.6.0"
regex = "1.11.1"
fasthash = "0.4.0"